blueprint:
  name: "Ping Dead Z-Wave Devices (v1.0.2)"
  description: |
    Pings all dead Z-Wave devices to try and wake them.
    
    This blueprint requires a specific template sensor. Please add
    the following code to your `sensor.yaml` file (or a similar
    file included in your configuration.yaml) and restart Home Assistant.

    ```yaml
    - platform: template
      sensors:
        dead_zwave_devices:
          friendly_name: "Dead ZWave Devices"
          unique_id: dead_zwave_devices
          unit_of_measurement: "entities"
          # --- UPDATED value_template ---
          # This template now calculates the count directly to prevent race conditions.
          value_template: >
            {% set exclude_filter = ['sensor.usb_controller_status'] %}
            {{
              expand(integration_entities('Z-Wave JS'))
              | rejectattr("entity_id", "in", exclude_filter)
              | selectattr("entity_id", "search", "node_status")
              | selectattr('state', 'in', ['dead', 'unavailable', 'unknown'])
              | list
              | count
            }}
          # --- END of update ---
          attribute_templates:
            entity_id: >
              {% set exclude_filter = ['sensor.usb_controller_status'] %}
              {{
                expand(integration_entities('Z-Wave JS'))
                | rejectattr("entity_id", "in", exclude_filter)
                | selectattr("entity_id", "search", "node_status")
                | selectattr('state', 'in', ['dead', 'unavailable', 'unknown'])
                | map(attribute="object_id")
                | map('regex_replace', find='(.*)_node_status', replace='button.\\1_ping', ignorecase=False)
                | list
              }}
    ```
  domain: automation
  input:
    dead_zwave_sensor:
      name: "Dead Z-Wave Sensor"
      description: "Select the template sensor that counts dead Z-Wave devices (e.g., sensor.dead_zwave_devices)."
      selector:
        entity:
          domain: sensor

trigger:
  # This triggers on any state change, which includes attribute changes.
  - platform: state
    entity_id: !input dead_zwave_sensor

condition:
  # Only run if the sensor value (count) is greater than 0.
  - condition: numeric_state
    entity_id: !input dead_zwave_sensor
    above: 0

action:
  # Call the button.press service
  - service: button.press
    # The target entities are pulled from the sensor's 'entity_id' attribute.
    # --- FIX: Added | default([]) to pass blueprint validation ---
    target:
      entity_id: "{{ state_attr(!input('dead_zwave_sensor'), 'entity_id') | default([]) }}"
  
  # Optional: Add a log entry to know when it has run.
  - service: system_log.write
    data:
      level: info
      logger: zwave_pinger_blueprint
      # --- FIX: Added | default([]) to prevent logging errors during validation ---
      message: "Attempted to ping dead Z-Wave devices: {{ state_attr(!input('dead_zwave_sensor'), 'entity_id') | default('Unknown') }}"

mode: single
