blueprint:
  name: "Ping Dead Z-Wave Devices"
  description: |
    Pings all dead Z-Wave devices to try and wake them.
    
    This blueprint requires a specific template sensor that
    counts dead devices and lists their 'button.ping' entities
    in an attribute named 'entity_id'.
  domain: automation
  input:
    dead_zwave_sensor:
      name: "Dead Z-Wave Sensor"
      description: "Select the template sensor that counts dead Z-Wave devices (e.g., sensor.dead_zwave_devices)."
      selector:
        entity:
          domain: sensor

trigger:
  # This triggers on any state change, which includes attribute changes.
  - platform: state
    entity_id: !input dead_zwave_sensor

condition:
  # Only run if the sensor value (count) is greater than 0.
  - condition: numeric_state
    entity_id: !input dead_zwave_sensor
    above: 0

action:
  # Call the button.press service
  - service: button.press
    # The target entities are pulled from the sensor's 'entity_id' attribute.
    target:
      entity_id: "{{ state_attr(!input('dead_zwave_sensor'), 'entity_id') }}"
  
  # Optional: Add a log entry to know when it has run.
  - service: system_log.write
    data:
      level: info
      logger: zwave_pinger_blueprint
      message: "Attempted to ping dead Z-Wave devices: {{ state_attr(!input('dead_zwave_sensor'), 'entity_id') }}"

mode: single
