blueprint:
  name: "Ping Dead Z-Wave Devices"
  description: |
    Pings all dead Z-Wave devices to try and wake them. (v1.0.6)
    
    This blueprint requires a specific template sensor. Please add
    the following code to your `configuration.yaml` file (or a `sensors.yaml` 
    file included from it). Restart Home Assistant after adding.

    ```yaml
    # Add this to your configuration.yaml
    template:
      - sensor:
          - name: "Dead ZWave Devices"
            unique_id: dead_zwave_devices
            unit_of_measurement: "entities"
            # This template now calculates the count directly to prevent race conditions.
            state: >
              {% set exclude_filter = ['sensor.usb_controller_status'] %}
              {{
                expand(integration_entities('Z-Wave JS'))
                | rejectattr("entity_id", "in", exclude_filter)
                | selectattr("entity_id", "search", "node_status")
                | selectattr('state', 'in', ['dead', 'unavailable', 'unknown'])
                | list
                | count
              }}
            attributes:
              entity_id: >
                {% set exclude_filter = ['sensor.usb_controller_status'] %}
                {{
                  expand(integration_entities('Z-Wave JS'))
                  | rejectattr("entity_id", "in", exclude_filter)
                  | selectattr("entity_id", "search", "node_status")
                  | selectattr('state', 'in', ['dead', 'unavailable', 'unknown'])
                  | map(attribute="object_id")
                  | map('regex_replace', find='(.*)_node_status', replace='button.\\1_ping', ignorecase=False)
                  | list
                }}
    ```
  domain: automation
  input:
    dead_zwave_sensor:
      name: "Dead Z-Wave Sensor"
      description: "Select the template sensor that counts dead Z-Wave devices (e.g., sensor.dead_zwave_devices)."
      selector:
        entity:
          domain: sensor

trigger:
  # This triggers on any state change, which includes attribute changes.
  - platform: state
    entity_id: !input dead_zwave_sensor

condition:
  # Only run if the sensor value (count) is greater than 0.
  - condition: numeric_state
    entity_id: !input dead_zwave_sensor
    above: 0

# --- VALIDATION FIX v1.0.6 ---
# The entire action block is moved into a 'choose' statement.
# This satisfies the HA validator, as the templates are
# only evaluated *after* the condition (that the sensor exists) is met.
action:
  - choose:
      # Check that the user has actually selected a sensor
      - conditions:
          - "{{ input('dead_zwave_sensor') is not none }}"
        sequence:
          # Call the button.press service
          - service: button.press
            target:
              entity_id: >
                {{ state_attr(input('dead_zwave_sensor'), 'entity_id') | default([]) }}
          
          # Optional: Add a log entry to know when it has run.
          - service: system_log.write
            data:
              level: info
              logger: zwave_pinger_blueprint
              # --- TEMPLATE FIX v1.0.6 ---
              # Changed !input() to input() for consistency.
              message: "Attempted to ping dead Z-Wave devices: {{ state_attr(input('dead_zwave_sensor'), 'entity_id') | default('No entities found') }}"
    # Fallback in case no sensor is selected (this will do nothing, but is good practice)
    default: []

mode: single
